* Map Operations

** Introduction: Loop Patterns

We've written a /lot/ of loops in this course so far. You're gaining practice and mastery with them, to the point where you might have started to recognize /patterns/ in all these loops.

Some of the types of loops you've encountered are:

1. Loops that hit every even or odd value, or every 3rd or 4th, skipping over some.
2. Loops that check each value against a condition, acting differently with different kinds of values.
3. Loops that transform each value in the array in some way, like doubling each number, getting the initials of each name, or extracting a property from each object.
4. Loops that look at the value before or after the current one, combining values in myriad ways.
5. Loops that loop through a series of values to give you one value, like an average of numbers, or how often each word appears in a sentence.

In the world of production apps, some of these types of loops appear over and over again. Others don't come up very often at all, but make for good learning exercises.

Today we're going to look at one particular type of loop that you find all the time in real-world apps: the map operation (number 3 in the preceding list).

We'll take a look at the mapping operation by deconstructing and generalizing mapping loops, so we can understand the /how/ and the /why/ of using them.

** Manual Mapping - looking at some examples
** Manual Mapping - We Do
** Taking A Step Back - creating a HOF forEach
** Creating a map HOF
** Using One For Nitter
** Warmup
Let's say we've got the following array:

#+NAME: people
#+begin_src js
const people = ["Colin", "Tim", "Mariella"];
#+end_src

#+NAME: mapped-people
#+begin_src js
<<people>>
const attendanceQuestions = people.map((person) => `Is ${person} here today?`)
#+end_src

#+begin_src js
<<mapped-people>>
console.log(attendanceQuestions)
#+end_src

#+RESULTS:
: [
:   'Is Colin here today?',
:   'Is Tim here today?',
:   'Is Mariella here today?'
: ]


** Nitter

#+NAME: tweets
#+begin_src js
const tweets = [
  {
    username: 'dril',
    text: 'Update from the good time line—Bacion is legal to eat at work thanks to President Banksy in the whitehouse, now known as the star wars house',
    displayName: 'wint',
    postId: 2,
    likes: 3999,
    replies: 137
  },
  {
    username: 'Leemanish',
    displayName: 'blake',
    text: 'Sick of having to go to 2 different huts to buy pizza & sunglasses.',
    postId: 3,
    likes: 4736,
    replies: 15
  },
  {
    username: 'queer_queenie',
    displayName: 'Queenie',
    text: `i hold a gender reveal party. all my relatives wait as i pull off the cake cover. the icing says "gender is a spectrum". it's too late, i have the powerpoint up`,
    postId: 4,
    likes: 8349,
    replies: 132
  },
  {
    username: 'phranqueigh',
    displayName: 'Frankie Zelnick',
    text: "How dare you call me mentally unstable, on this, the day of my cat's quinceanera.",
    postId: 5,
    likes: 3612,
    replies: 16
  }
];

console.log(tweets)
#+end_src

#+RESULTS: tweets
#+begin_example
[
  {
    username: 'dril',
    text: 'Update from the good time line—Bacion is legal to eat at work thanks to President Banksy in the whitehouse, now known as the star wars house',
    displayName: 'wint',
    postId: 2,
    likes: 3999,
    replies: 137
  },
  {
    username: 'Leemanish',
    displayName: 'blake',
    text: 'Sick of having to go to 2 different huts to buy pizza & sunglasses.',
    postId: 3,
    likes: 4736,
    replies: 15
  },
  {
    username: 'queer_queenie',
    displayName: 'Queenie',
    text: `i hold a gender reveal party. all my relatives wait as i pull off the cake cover. the icing says "gender is a spectrum". it's too late, i have the powerpoint up`,
    postId: 4,
    likes: 8349,
    replies: 132
  },
  {
    username: 'phranqueigh',
    displayName: 'Frankie Zelnick',
    text: "How dare you call me mentally unstable, on this, the day of my cat's quinceanera.",
    postId: 5,
    likes: 3612,
    replies: 16
  }
]
#+end_example

#+NAME: convertNumber
#+begin_src js
const convertNumber = (number) => {
  if (number < 1000) {
    return number.toString();
  }

  return (Math.floor(number / 100) / 10).toString() + 'K'
}
#+end_src

#+NAME: getDisplayTweets
#+begin_src js
const getDisplayTweets = (tweet) => (`${tweet.displayName}
@${tweet.username}

${tweet.text}

${tweet.likes} Likes   ${tweet.replies} Replies`)
#+end_src

#+NAME: getDisplayTweetsColor
#+begin_src js
<<convertNumber>>

const getDisplayTweets = (tweet) => (`${tweet.displayName.blue}
@${tweet.username}

${tweet.text}

💙 ${convertNumber(tweet.likes).bold}  🗨 ${convertNumber(tweet.replies).bold}  🔗 Copy Link`)
#+end_src

#+RESULTS: getDisplayTweetsColor

#+begin_src js
<<tweets>>
<<getDisplayTweets>>
const tweet = getDisplayTweets(tweets[0]);
console.log(tweet);
#+end_src

#+RESULTS:
: wint
: @dril
: 
: Update from the good time line—Bacion is legal to eat at work thanks to President Banksy in the whitehouse, now known as the star wars house
: 
: 2139 Likes   NaN Replies


#+begin_src js 
<<tweets>>

const tweetStrings = [];
for (let i = 0; i < tweets.length; i++) {
  const tweet = tweets[i];
  const tweetString = `${tweet.displayName}
@${tweet.username}

${tweet.text}

${tweet.retweets} Retweets   ${tweet.likes} Likes   ${tweet.replies} Replies`
  tweetStrings.push(tweetString);
}

tweetStrings.forEach((tweetString) => console.log(tweetString + '\n\n'))
#+end_src

#+RESULTS:
#+begin_example
wint
@dril

Update from the good time line—Bacion is legal to eat at work thanks to President Banksy in the whitehouse, now known as the star wars house

1200 Retweets   8200 Likes   28 Replies


blake
@Leemanish

Sick of having to go to 2 different huts to buy pizza & sunglasses.

2900 Retweets   6300 Likes   210 Replies


Queenie
@queer_queenie

i hold a gender reveal party. all my relatives wait as i pull off the cake cover. the icing says "gender is a spectrum". it's too late, i have the powerpoint up

16900 Retweets   70600 Likes   730 Replies


Frankie Zelnick
@phranqueigh

How dare you call me mentally unstable, on this, the day of my cat's quinceanera.

5000 Retweets   9300 Likes   121 Replies


#+end_example

This is a library we'll pull in to allow us to make our terminal output prettier. We'll be using it exclusively to get bold text in our tweets.

#+NAME: imports
#+begin_src js
const colors = require('colors');
#+end_src

Now we can di
#+begin_src js :tangle nitter.js
<<imports>>

<<tweets>>

<<getDisplayTweetsColor>>

const displayTweets = tweets.map(getDisplayTweets);
displayTweets.forEach((displayTweet) => console.log(displayTweet + '\n'));
#+end_src

#+RESULTS:
